# LARAVEL - CSRF

# CSRF Tokens & SPAs
// If you are building an SPA that is utilizing Laravel as an API backend, you should consult the Laravel Sanctum documentation for information on authenticating with your API and protecting against CSRF vulnerabilities.

# Excluding URIs From CSRF Protection
/**
Sometimes you may wish to exclude a set of URIs from CSRF protection. 
For example, if you are using Stripe to process payments and are utilizing their webhook system, you will need 
to exclude your Stripe webhook handler route from CSRF protection since Stripe will not know what CSRF token to send to your routes.
*/

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    protected $except = [
        'stripe/*',	// route?
        'http://example.com/foo/bar',
        'http://example.com/foo/*',
    ];
}

# X-CSRF-TOKEN
// In addition to checking for the CSRF token as a POST parameter, the App\Http\Middleware\VerifyCsrfToken middleware will also check for the X-CSRF-TOKEN request header. 
// You could, for example, store the token in an HTML meta tag:

<meta name="csrf-token" content="{{ csrf_token() }}">


// Then, you can instruct a library like jQuery to automatically add the token to all request headers. 
// This provides simple, convenient CSRF protection for your AJAX based applications using legacy JavaScript technology:

$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});

# X-XSRF-TOKEN
/**
Laravel stores the current CSRF token in an encrypted XSRF-TOKEN cookie that is included with each response generated by the framework. 
You can use the cookie value to set the X-XSRF-TOKEN request header.

This cookie is primarily sent as a developer convenience since some JavaScript frameworks and libraries, like Angular and Axios, automatically place its value in the X-XSRF-TOKEN header on same-origin requests.


By default, the resources/js/bootstrap.js file includes the Axios HTTP library which will automatically send the X-XSRF-TOKEN header for you.
*/